[package]
name = "peach"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["full"] }
tokio-stream = { version = "0.1" }

bytes = "1.0.0"
futures = { version = "0.3.0", features = ["thread-pool"]}