[package]
name = "serde"
version = "0.1.0"
authors = ["Michael Angerman <stormasm@gmail.com>"]
edition = "2018"

[dependencies]
redis = "0.12.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
